### ISSUE TITLE
The SSP board members to individually sign the SSP in TCC statutes

### ISSUE THREAD

**Issue by meijer** [simplesamlphp/governance#2]
The formal request for SSP to become a program in TCC has been sent to the TCC board. A signature page was received, for each individual SSP board member to sign. Once all have signed, SSP will be established as a programme in TCC (https://commonsconservancy.org)

To each board member: please comment to this issue once you've signed.

**Comment by meijer** [comment]
I've signed on 24.3.2021.

**Comment by jaimeperez** [comment]
26.03.2021

**Comment by meijer** [comment]
Niels signed, and on 21 April 2021 we received confirmation from Michiel Leenaars of TCC that SSP is now established as a programme in The Commons Conservancy. Hurray! On 27. april 2021 we received conformation we were now visible on the TCC website in the programmes directory: https://commonsconservancy.org/programmes/

I suggested to Michiel that a digital TCC "birth certificate" might be nice for new programmes, as now it felt a bit uncelebrated, the birth of a new programme ;)
