### ISSUE TITLE
Transfer management of simplesaml website to community

### ISSUE THREAD

**Issue by meijer** [simplesamlphp/governance#9]
The website is currently passively managed by Uninett (kept in the air, but no changes made to content). For the SimpleSAMLphp community to take charge of its destination it needs to take charge of its communication.

**Comment by meijer** [comment]
Situation today:
website generation code is written to run on Uninett’s Kubernetes infrastructure
Two repositories (“hybrid monster”)
one builds the website and is generated from Uninetts private gitlab repository on gitlab.uninett.no
the documentation site is version-spesific and is retrieved from the public SSP repository on Github

What runs on the PaaS (Uninett Kubernetes infra):
a container which contains (ha ha) the SimpleSAMLphp web page www.simplesamlphp.org
something which retrieves the documentation and makes it available via docs.simplesamlphp.org
the current framework used for documentation is ReadTheDocs

The current website does not run on Github pages. Running on Github pages is currently considered an interesting dream, but a dream. 

The website repository is available on Github but because the build-system at Uninett is being / has been changed, this repository lacks the newest website versions. 

The conclusion is that in order to move website generation to a community-controlled environment, some lift and some modified shift looks to be needed. It was suggested to either take everything out statically, or generate it from the repo. 

The current release process:
the build process uses a docker “release build” container from the SSP code repository , to build a new SSP release from the relevant source code repos
Uninett has a wiki (internal) which documents this process step-by-step



Domain name transfer:
simplesamlphp.org
same domain in several other TLDs which are only used to redirect to simplesamlphp.org

**Comment by thijskh** [comment]
The current website is also not quite up to par with modern HTML standards, uses Google Analytics and Google CSE (:scream_cat:) and contains a lot of outdated info.

How about we just try to whip something simple together from scratch and move content into that? An MVP website on GH pages which we can always augment.

**Comment by meijer** [comment]
That was also my suggestion at the last board meeting, but there was no consensus yet. 

Just had a discussion with Niels. Our proposal:
- documentation to be stored in github and published via github pages, via docs.simplesamlphp.org
- rely on Github for dynamic development-related content like which tickets need to be resolved for a new release (github project in stead of current roadmap page) and release information (releases). 
- create a new "communication" website www.simplesamlphp. In some future where we have a communication resource it would be nice to have the ability to post news articles, but at the moment we don't have anyone to do that, so currently it's not a requirement. So while a future "communication site" could be hosted with e.g. a wordpress hoster, for now a quick check of what type of info is currently available shows that presenting some 10 pretty static pages through github pages would be quicker, and a sufficiently good result for now. 

Thoughts?

**Comment by thijskh** [comment]
1. Yes.
2. Yes or even simpler: just link to the overviews Github already produces (milestones, releases)
3. See not much advatange to Wordpress, also in GH pages its easy to create news items etc. Doubt we will ever require fancy markup and layouting.

So let's just do it?

**Comment by meijer** [comment]
Thijs,

(2): that's what I meant too. Fully utilise the tooling Github already gives us to do these things. 
(3): for developer-oriented communication I think you're mostly right. However, for SSP to become long term sustainable we'll need to do some fund raising, gut feeling says that requires something slightly different communication wise. But we'll leave that to the communications/community person we intend to engage.  

Niels is picking up on (1) and (2), but others please feel free to help out, e.g. by volunteering to redo some of the new pages in markdown. One thing we'll need is an "about" page.

**Comment by olavmrk** [comment]
Some clarifications and comments as per @meijer request:

* The current website is only at simplesamlphp.org -- there is not yet a docs.simplesamlphp.org site.
* The domains that we have configured redirects for are:
  * simplesamlphp.no
  * simplesamlphp.com
  * simplesamlphp.net
* There is also a redirect for www.simplesamlphp.org to simplesamlphp.org

Here is the release process notes from our internal wiki:

> The release process is also online in the wiki at Github.
>
> 1. Version bump in the Configuration class getVersion() method, also in the spec file for rpm. And composer.json and in the changelog file in the docs. Remember to run `composer update --lock` after updating the version number in `composer.json`.
> 2. Adjust changelog with issue, and also upgrade guide if applicable.
> 3. When running composer and adjusting lock-files, this is done using the minimum supported php version.
> 4. Good practice to sign the commits, especially for new releases. Might be possible to force GH to make sure, per branch.
> 5. Building new release tarball done with upstream script using docker to get the correct php version. The script and docs are in the `release-builder` repo.
> 6. Create tag, GH release notes and upload tarball with shasum.
> 7. Push pending changes to the website, including any security issues.
> 8. Also replicate the changes to https://github.com/simplesamlphp/simplesamlphp.github.io
> 9. Email the simplesamlphp-announce mailing list. (Users) (there is also ml for -dev, and a dead one for translators)​​

**Comment by thijskh** [comment]
So, https://github.com/simplesamlphp/simplesamlphp.github.io already exists and seems like a reasonable representation of the current website. See: https://simplesamlphp.github.io

The release branch is up to date, the master branch is not, this is because the travis run seems to be broken (travis-ci.org is down anyway) so the build process needs to become a github action. If we fix the github action we already have an operational website with all the content from the current website.

Even the docs are rendered. But this is indeed not an ideal form. So best to move that to docs.simplesamlphp.org as proposed.

In any case it seems we quite already got what we need to transfer the website.

Of course then we can start actually cleaning up the website.

**Comment by surfnet-niels** [comment]
Docs top level directory is rendered, but all the links in it are broken.. @olavmrk I suspect there is a script somewhere that converts the markdown of the docs to the documentation pages using a local readthedocs. Would you happen to know where that script lives?

**Comment by thijskh** [comment]
I have fixed the build pipeline of simplesamlphp.github.io. This now just works and presents a website that is at least as good as the current one, except for the docs. So nothing more needed there. If we have an operational docs.simplesamlphp.org, we can link that from simplesamlphp.github.io and point simplesamlphp.org to simplesamlphp.github.io.

Then we can improve the actual content of the website further which is also much needed.

**Comment by olavmrk** [comment]
@surfnet-niels: I assume that you are thinking of the documentation links at [simplesamlphp.github.io/docs](https://simplesamlphp.github.io/docs/)? I am not familiar with that documentation system, so I do not know how it works.

The existing documentation is rendered using [php-markdown](https://github.com/michelf/php-markdown).

I am not aware of any place where we are using readthedocs.

**Comment by thijskh** [comment]
This is done I think?
